### PR TITLE
Added dialog for the user to confirm before navigating to browser

### LINKED ISSUE #7: Don't automatically open the browser after program completed
After the generation is completed don’t open the browser immediately. Show the link that will be opened and wait for the user to press enter to avoid surprises.

### PR DESCRIPTION
**Pull request by KrishKayc**
Screenshot from 2020-10-21 18-46-24

### CODE REVIEW

**Comment by alimgiray** [comment]
Hi @KrishKayc, unfortunately this is not working on my computer, macOS Catalina while using iTerm2. 

While this third party library seems nice, can you implement something more native and safe, like this:

Screen Shot 2020-10-21 at 17 12 12

**Comment by KrishKayc** [comment]
@alimgiray Sure. I saw that the package was compatible with mac, windows and linux hence used it. Will change it and update this PR

**Comment by KrishKayc** [comment]
@alimgiray Updated the PR. Implemented CLI confirm instead of UI alert. Works fine in linux.

**Comment by alimgiray** [comment]
@KrishKayc, It's perfect. Thank you!

**Pull request merged**
